# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import atlas_pb2 as atlas__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in atlas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AtlasStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPrimitive = channel.unary_unary(
                '/robonix.atlas.Atlas/RegisterPrimitive',
                request_serializer=atlas__pb2.RegisterRequest.SerializeToString,
                response_deserializer=atlas__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.RegisterService = channel.unary_unary(
                '/robonix.atlas.Atlas/RegisterService',
                request_serializer=atlas__pb2.RegisterRequest.SerializeToString,
                response_deserializer=atlas__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.RegisterSkill = channel.unary_unary(
                '/robonix.atlas.Atlas/RegisterSkill',
                request_serializer=atlas__pb2.RegisterRequest.SerializeToString,
                response_deserializer=atlas__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/robonix.atlas.Atlas/Unregister',
                request_serializer=atlas__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=atlas__pb2.UnregisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/robonix.atlas.Atlas/Heartbeat',
                request_serializer=atlas__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=atlas__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.SetLifecycleState = channel.unary_unary(
                '/robonix.atlas.Atlas/SetLifecycleState',
                request_serializer=atlas__pb2.SetLifecycleStateRequest.SerializeToString,
                response_deserializer=atlas__pb2.SetLifecycleStateResponse.FromString,
                _registered_method=True)
        self.DeclareCapability = channel.unary_unary(
                '/robonix.atlas.Atlas/DeclareCapability',
                request_serializer=atlas__pb2.DeclareCapabilityRequest.SerializeToString,
                response_deserializer=atlas__pb2.DeclareCapabilityResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/robonix.atlas.Atlas/Query',
                request_serializer=atlas__pb2.QueryRequest.SerializeToString,
                response_deserializer=atlas__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ConnectCapability = channel.unary_unary(
                '/robonix.atlas.Atlas/ConnectCapability',
                request_serializer=atlas__pb2.ConnectCapabilityRequest.SerializeToString,
                response_deserializer=atlas__pb2.ConnectCapabilityResponse.FromString,
                _registered_method=True)
        self.DisconnectCapability = channel.unary_unary(
                '/robonix.atlas.Atlas/DisconnectCapability',
                request_serializer=atlas__pb2.DisconnectCapabilityRequest.SerializeToString,
                response_deserializer=atlas__pb2.DisconnectCapabilityResponse.FromString,
                _registered_method=True)
        self.QueryContract = channel.unary_unary(
                '/robonix.atlas.Atlas/QueryContract',
                request_serializer=atlas__pb2.QueryContractRequest.SerializeToString,
                response_deserializer=atlas__pb2.QueryContractResponse.FromString,
                _registered_method=True)
        self.ListContracts = channel.unary_unary(
                '/robonix.atlas.Atlas/ListContracts',
                request_serializer=atlas__pb2.ListContractsRequest.SerializeToString,
                response_deserializer=atlas__pb2.ListContractsResponse.FromString,
                _registered_method=True)
        self.InspectAtlas = channel.unary_unary(
                '/robonix.atlas.Atlas/InspectAtlas',
                request_serializer=atlas__pb2.InspectAtlasRequest.SerializeToString,
                response_deserializer=atlas__pb2.InspectAtlasResponse.FromString,
                _registered_method=True)


class AtlasServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterPrimitive(self, request, context):
        """Registration -- one RPC per CapabilityProvider kind.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSkill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Liveness + lifecycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLifecycleState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareCapability(self, request, context):
        """Capability binding.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Discovery -- one Query RPC, kind carried in the request body.
        Consumers wanting a flat capability list flatten `CapabilityProvider.capabilities`
        themselves; each Capability already carries provider_id / provider_kind.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectCapability(self, request, context):
        """Channels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryContract(self, request, context):
        """Contracts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContracts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectAtlas(self, request, context):
        """Debug.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtlasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPrimitive': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPrimitive,
                    request_deserializer=atlas__pb2.RegisterRequest.FromString,
                    response_serializer=atlas__pb2.RegisterResponse.SerializeToString,
            ),
            'RegisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterService,
                    request_deserializer=atlas__pb2.RegisterRequest.FromString,
                    response_serializer=atlas__pb2.RegisterResponse.SerializeToString,
            ),
            'RegisterSkill': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSkill,
                    request_deserializer=atlas__pb2.RegisterRequest.FromString,
                    response_serializer=atlas__pb2.RegisterResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=atlas__pb2.UnregisterRequest.FromString,
                    response_serializer=atlas__pb2.UnregisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=atlas__pb2.HeartbeatRequest.FromString,
                    response_serializer=atlas__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SetLifecycleState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLifecycleState,
                    request_deserializer=atlas__pb2.SetLifecycleStateRequest.FromString,
                    response_serializer=atlas__pb2.SetLifecycleStateResponse.SerializeToString,
            ),
            'DeclareCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareCapability,
                    request_deserializer=atlas__pb2.DeclareCapabilityRequest.FromString,
                    response_serializer=atlas__pb2.DeclareCapabilityResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=atlas__pb2.QueryRequest.FromString,
                    response_serializer=atlas__pb2.QueryResponse.SerializeToString,
            ),
            'ConnectCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectCapability,
                    request_deserializer=atlas__pb2.ConnectCapabilityRequest.FromString,
                    response_serializer=atlas__pb2.ConnectCapabilityResponse.SerializeToString,
            ),
            'DisconnectCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectCapability,
                    request_deserializer=atlas__pb2.DisconnectCapabilityRequest.FromString,
                    response_serializer=atlas__pb2.DisconnectCapabilityResponse.SerializeToString,
            ),
            'QueryContract': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryContract,
                    request_deserializer=atlas__pb2.QueryContractRequest.FromString,
                    response_serializer=atlas__pb2.QueryContractResponse.SerializeToString,
            ),
            'ListContracts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContracts,
                    request_deserializer=atlas__pb2.ListContractsRequest.FromString,
                    response_serializer=atlas__pb2.ListContractsResponse.SerializeToString,
            ),
            'InspectAtlas': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectAtlas,
                    request_deserializer=atlas__pb2.InspectAtlasRequest.FromString,
                    response_serializer=atlas__pb2.InspectAtlasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.atlas.Atlas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.atlas.Atlas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Atlas:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterPrimitive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/RegisterPrimitive',
            atlas__pb2.RegisterRequest.SerializeToString,
            atlas__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/RegisterService',
            atlas__pb2.RegisterRequest.SerializeToString,
            atlas__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/RegisterSkill',
            atlas__pb2.RegisterRequest.SerializeToString,
            atlas__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/Unregister',
            atlas__pb2.UnregisterRequest.SerializeToString,
            atlas__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/Heartbeat',
            atlas__pb2.HeartbeatRequest.SerializeToString,
            atlas__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLifecycleState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/SetLifecycleState',
            atlas__pb2.SetLifecycleStateRequest.SerializeToString,
            atlas__pb2.SetLifecycleStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclareCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/DeclareCapability',
            atlas__pb2.DeclareCapabilityRequest.SerializeToString,
            atlas__pb2.DeclareCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/Query',
            atlas__pb2.QueryRequest.SerializeToString,
            atlas__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/ConnectCapability',
            atlas__pb2.ConnectCapabilityRequest.SerializeToString,
            atlas__pb2.ConnectCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/DisconnectCapability',
            atlas__pb2.DisconnectCapabilityRequest.SerializeToString,
            atlas__pb2.DisconnectCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/QueryContract',
            atlas__pb2.QueryContractRequest.SerializeToString,
            atlas__pb2.QueryContractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContracts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/ListContracts',
            atlas__pb2.ListContractsRequest.SerializeToString,
            atlas__pb2.ListContractsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectAtlas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/InspectAtlas',
            atlas__pb2.InspectAtlasRequest.SerializeToString,
            atlas__pb2.InspectAtlasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
