# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lifecycle.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'lifecycle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flifecycle.proto\x12\x11robonix.lifecycle\"\x92\x01\n\x0e\x44river_Request\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\r\x12\x13\n\x0b\x63onfig_json\x18\x02 \x01(\t\"Z\n\x12\x44river_RequestEnum\x12\x0c\n\x08\x43MD_INIT\x10\x00\x12\x10\n\x0c\x43MD_ACTIVATE\x10\x01\x12\x12\n\x0e\x43MD_DEACTIVATE\x10\x02\x12\x10\n\x0c\x43MD_SHUTDOWN\x10\x03\";\n\x0f\x44river_Response\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05state\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lifecycle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVER_REQUEST']._serialized_start=39
  _globals['_DRIVER_REQUEST']._serialized_end=185
  _globals['_DRIVER_REQUEST_DRIVER_REQUESTENUM']._serialized_start=95
  _globals['_DRIVER_REQUEST_DRIVER_REQUESTENUM']._serialized_end=185
  _globals['_DRIVER_RESPONSE']._serialized_start=187
  _globals['_DRIVER_RESPONSE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
