# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memgraph.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'memgraph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_msgs_pb2 as std__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ememgraph.proto\x12\x10robonix.memgraph\x1a\x0estd_msgs.proto\";\n\x0f\x43ompact_Request\x12(\n\x07trigger\x18\x01 \x01(\x0b\x32\x17.robonix.std_msgs.Empty\"C\n\x10\x43ompact_Response\x12/\n\rresponse_json\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.String\"B\n\x10Remember_Request\x12.\n\x0crequest_json\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.String\"D\n\x11Remember_Response\x12/\n\rresponse_json\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.String\"@\n\x0eSearch_Request\x12.\n\x0crequest_json\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.String\"B\n\x0fSearch_Response\x12/\n\rresponse_json\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Stringb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memgraph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPACT_REQUEST']._serialized_start=52
  _globals['_COMPACT_REQUEST']._serialized_end=111
  _globals['_COMPACT_RESPONSE']._serialized_start=113
  _globals['_COMPACT_RESPONSE']._serialized_end=180
  _globals['_REMEMBER_REQUEST']._serialized_start=182
  _globals['_REMEMBER_REQUEST']._serialized_end=248
  _globals['_REMEMBER_RESPONSE']._serialized_start=250
  _globals['_REMEMBER_RESPONSE']._serialized_end=318
  _globals['_SEARCH_REQUEST']._serialized_start=320
  _globals['_SEARCH_REQUEST']._serialized_end=384
  _globals['_SEARCH_RESPONSE']._serialized_start=386
  _globals['_SEARCH_RESPONSE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
