# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_msgs_pb2 as std__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x12\x0erobonix.memory\x1a\x0estd_msgs.proto\";\n\x0f\x43ompact_Request\x12(\n\x07trigger\x18\x01 \x01(\x0b\x32\x17.robonix.std_msgs.Empty\"=\n\x10\x43ompact_Response\x12)\n\x07summary\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.String\"9\n\x0cSave_Request\x12)\n\x07\x63ontent\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.String\"?\n\rSave_Response\x12.\n\x0c\x63onfirmation\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.String\"9\n\x0eSearch_Request\x12\'\n\x05query\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.String\"<\n\x0fSearch_Response\x12)\n\x07results\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Stringb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPACT_REQUEST']._serialized_start=48
  _globals['_COMPACT_REQUEST']._serialized_end=107
  _globals['_COMPACT_RESPONSE']._serialized_start=109
  _globals['_COMPACT_RESPONSE']._serialized_end=170
  _globals['_SAVE_REQUEST']._serialized_start=172
  _globals['_SAVE_REQUEST']._serialized_end=229
  _globals['_SAVE_RESPONSE']._serialized_start=231
  _globals['_SAVE_RESPONSE']._serialized_end=294
  _globals['_SEARCH_REQUEST']._serialized_start=296
  _globals['_SEARCH_REQUEST']._serialized_end=353
  _globals['_SEARCH_RESPONSE']._serialized_start=355
  _globals['_SEARCH_RESPONSE']._serialized_end=415
# @@protoc_insertion_point(module_scope)
