# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statistics_msgs.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'statistics_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import builtin_interfaces_pb2 as builtin__interfaces__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15statistics_msgs.proto\x12\x17robonix.statistics_msgs\x1a\x18\x62uiltin_interfaces.proto\"\x87\x02\n\x0eMetricsMessage\x12\x1f\n\x17measurement_source_name\x18\x01 \x01(\t\x12\x16\n\x0emetrics_source\x18\x02 \x01(\t\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x36\n\x0cwindow_start\x18\x04 \x01(\x0b\x32 .robonix.builtin_interfaces.Time\x12\x35\n\x0bwindow_stop\x18\x05 \x01(\x0b\x32 .robonix.builtin_interfaces.Time\x12?\n\nstatistics\x18\x06 \x03(\x0b\x32+.robonix.statistics_msgs.StatisticDataPoint\"5\n\x12StatisticDataPoint\x12\x11\n\tdata_type\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x01\"\x83\x02\n\x11StatisticDataType\"\xed\x01\n\x15StatisticDataTypeEnum\x12&\n\"STATISTICS_DATA_TYPE_UNINITIALIZED\x10\x00\x12 \n\x1cSTATISTICS_DATA_TYPE_AVERAGE\x10\x01\x12 \n\x1cSTATISTICS_DATA_TYPE_MINIMUM\x10\x02\x12 \n\x1cSTATISTICS_DATA_TYPE_MAXIMUM\x10\x03\x12\x1f\n\x1bSTATISTICS_DATA_TYPE_STDDEV\x10\x04\x12%\n!STATISTICS_DATA_TYPE_SAMPLE_COUNT\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICSMESSAGE']._serialized_start=77
  _globals['_METRICSMESSAGE']._serialized_end=340
  _globals['_STATISTICDATAPOINT']._serialized_start=342
  _globals['_STATISTICDATAPOINT']._serialized_end=395
  _globals['_STATISTICDATATYPE']._serialized_start=398
  _globals['_STATISTICDATATYPE']._serialized_end=657
  _globals['_STATISTICDATATYPE_STATISTICDATATYPEENUM']._serialized_start=420
  _globals['_STATISTICDATATYPE_STATISTICDATATYPEENUM']._serialized_end=657
# @@protoc_insertion_point(module_scope)
