# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vitals.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'vitals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvitals.proto\x12\x0erobonix.vitals\"\x93\x01\n\rBodyComponent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x12\n\nerror_code\x18\x04 \x01(\r\x12\x0f\n\x07\x65nabled\x18\x05 \x01(\x08\x12\n\n\x02id\x18\x06 \x01(\t\x12\x11\n\tparent_id\x18\x07 \x01(\t\x12\r\n\x05model\x18\x08 \x01(\t\"\xb5\x01\n\nBodyHealth\x12\x11\n\tbody_type\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\r\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x31\n\ncomponents\x18\x05 \x03(\x0b\x32\x1d.robonix.vitals.BodyComponent\"2\n\x0e\x42odyHealthEnum\x12\n\n\x06NORMAL\x10\x00\x12\t\n\x05\x46\x41ULT\x10\x01\x12\t\n\x05\x45STOP\x10\x02\"\x95\x01\n\x0f\x43omponentHealth\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06health\x18\x02 \x01(\r\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\x12\x11\n\tthreshold\x18\x05 \x01(\x02\"2\n\x13\x43omponentHealthEnum\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04WARN\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"]\n\nPowerState\x12\x17\n\x0f\x62\x61ttery_percent\x18\x01 \x01(\x02\x12\x0f\n\x07voltage\x18\x02 \x01(\x02\x12\x10\n\x08\x63harging\x18\x03 \x01(\x08\x12\x13\n\x0bremaining_s\x18\x04 \x01(\x03\"\xab\x01\n\x0eVitalsSnapshot\x12\r\n\x05ts_ns\x18\x01 \x01(\x04\x12)\n\x05power\x18\x02 \x01(\x0b\x32\x1a.robonix.vitals.PowerState\x12\x33\n\ncomponents\x18\x03 \x03(\x0b\x32\x1f.robonix.vitals.ComponentHealth\x12*\n\x06\x62odies\x18\x04 \x03(\x0b\x32\x1a.robonix.vitals.BodyHealth\"\x13\n\x11GetVitals_Request\"F\n\x12GetVitals_Response\x12\x30\n\x08snapshot\x18\x01 \x01(\x0b\x32\x1e.robonix.vitals.VitalsSnapshot\"\x16\n\x14StreamVitals_Request\"I\n\x15StreamVitals_Response\x12\x30\n\x08snapshot\x18\x01 \x01(\x0b\x32\x1e.robonix.vitals.VitalsSnapshotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vitals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BODYCOMPONENT']._serialized_start=33
  _globals['_BODYCOMPONENT']._serialized_end=180
  _globals['_BODYHEALTH']._serialized_start=183
  _globals['_BODYHEALTH']._serialized_end=364
  _globals['_BODYHEALTH_BODYHEALTHENUM']._serialized_start=314
  _globals['_BODYHEALTH_BODYHEALTHENUM']._serialized_end=364
  _globals['_COMPONENTHEALTH']._serialized_start=367
  _globals['_COMPONENTHEALTH']._serialized_end=516
  _globals['_COMPONENTHEALTH_COMPONENTHEALTHENUM']._serialized_start=466
  _globals['_COMPONENTHEALTH_COMPONENTHEALTHENUM']._serialized_end=516
  _globals['_POWERSTATE']._serialized_start=518
  _globals['_POWERSTATE']._serialized_end=611
  _globals['_VITALSSNAPSHOT']._serialized_start=614
  _globals['_VITALSSNAPSHOT']._serialized_end=785
  _globals['_GETVITALS_REQUEST']._serialized_start=787
  _globals['_GETVITALS_REQUEST']._serialized_end=806
  _globals['_GETVITALS_RESPONSE']._serialized_start=808
  _globals['_GETVITALS_RESPONSE']._serialized_end=878
  _globals['_STREAMVITALS_REQUEST']._serialized_start=880
  _globals['_STREAMVITALS_REQUEST']._serialized_end=902
  _globals['_STREAMVITALS_RESPONSE']._serialized_start=904
  _globals['_STREAMVITALS_RESPONSE']._serialized_end=977
# @@protoc_insertion_point(module_scope)
